In [ ]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [ ]:
Dataset1 = pd.read_csv("/content/drive/MyDrive/MyPersonalDataset/heart.csv")
Dataset1

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [ ]:
# shape
Dataset1.shape

(1025, 14)

In [ ]:
# duplicate value
Dataset1.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1020     True
1021     True
1022     True
1023     True
1024     True
Length: 1025, dtype: bool

In [ ]:
# total duplicate record
Dataset1.duplicated().sum()

723

In [ ]:
# to show the duplicate values
Dataset1.loc[Dataset1.duplicated(), :]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
15,34,0,1,118,210,0,1,192,0,0.7,2,0,2,1
31,50,0,1,120,244,0,1,162,0,1.1,2,0,2,1
43,46,1,0,120,249,0,0,144,0,0.8,2,0,3,0
55,55,1,0,140,217,0,1,111,1,5.6,0,0,3,0
61,66,0,2,146,278,0,0,152,0,0.0,1,1,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [ ]:
# drop the duplicate value
Dataset2 = Dataset1.drop_duplicates()
Dataset2

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
723,68,0,2,120,211,0,0,115,0,1.5,1,0,2,1
733,44,0,2,108,141,0,1,175,0,0.6,1,0,2,1
739,52,1,0,128,255,0,1,161,1,0.0,2,1,3,0
843,59,1,3,160,273,0,0,125,0,0.0,2,0,2,0
878,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [ ]:
Dataset2.shape

(302, 14)

In [ ]:
Dataset1.shape

(1025, 14)

In [ ]:
Dataset2.duplicated().sum()

0

In [ ]:
# splitting out dataset using drop
X = Dataset2.drop(columns = 'target')
X

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
723,68,0,2,120,211,0,0,115,0,1.5,1,0,2
733,44,0,2,108,141,0,1,175,0,0.6,1,0,2
739,52,1,0,128,255,0,1,161,1,0.0,2,1,3
843,59,1,3,160,273,0,0,125,0,0.0,2,0,2
878,54,1,0,120,188,0,1,113,0,1.4,1,1,3

In [ ]:
y = Dataset2[['target']]
y

     target
0         0
1         0
2         0
3         0
4         0
..      ...
723       1
733       1
739       0
843       0
878       0

[302 rows x 1 columns]

In [ ]:
# train test splitting
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.80, random_state = 0)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(241, 13)
(61, 13)
(241, 1)
(61, 1)

In [ ]:
# Feature Scaling Technique - Standard Scaler
from sklearn.preprocessing import StandardScaler

sc = StandardScaler() # object of StandardScaler
sc.fit(X_train)

StandardScaler()

In [ ]:
X_train_sc = sc.transform(X_train)
X_test_sc = sc.transform(X_test)

In [ ]:
X_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
81,49,1,2,118,149,0,0,126,0,0.8,2,3,2
193,69,1,3,160,234,1,0,131,0,0.1,1,1,2
70,59,1,0,170,326,0,0,140,1,3.4,0,0,3
719,52,1,0,108,233,1,1,147,0,0.1,2,3,3
628,69,0,3,140,239,0,1,151,0,1.8,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
425,51,0,0,130,305,0,1,142,1,1.2,1,0,3
271,44,1,1,120,263,0,1,173,0,0.0,2,0,3
143,34,1,3,118,182,0,0,174,0,0.0,2,0,2
50,58,0,3,150,283,1,0,162,0,1.0,2,0,2
232,60,1,0,125,258,0,0,141,1,2.8,1,1,3

In [ ]:
pd.DataFrame(X_train_sc)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,-0.564239,0.678680,1.089217,-0.717172,-1.817123,-0.425879,-1.068253,-1.062143,-0.704907,-0.233302,1.006803,2.350583,-0.570055
1,1.590778,0.678680,2.079788,1.708225,-0.221659,2.348087,-1.068253,-0.836613,-0.704907,-0.828734,-0.621650,0.305491,-0.570055
2,0.513270,0.678680,-0.891925,2.285700,1.505196,-0.425879,-1.068253,-0.430659,1.418626,1.978302,-2.250103,-0.717055,1.126035
3,-0.240986,0.678680,-0.891925,-1.294647,-0.240429,2.348087,0.824754,-0.114917,-0.704907,-0.828734,1.006803,2.350583,1.126035
4,1.590778,-1.473449,2.079788,0.553274,-0.127808,-0.425879,0.824754,0.065507,-0.704907,0.617315,1.006803,1.328037,-0.570055
...,...,...,...,...,...,...,...,...,...,...,...,...,...
236,-0.348737,-1.473449,-0.891925,-0.024201,1.111022,-0.425879,0.824754,-0.340447,1.418626,0.106945,-0.621650,-0.717055,1.126035
237,-1.102993,0.678680,0.098646,-0.601677,0.322675,-0.425879,0.824754,1.057838,-0.704907,-0.913795,1.006803,-0.717055,1.126035
238,-2.180502,0.678680,2.079788,-0.717172,-1.197708,-0.425879,-1.068253,1.102944,-0.704907,-0.913795,1.006803,-0.717055,-0.570055
239,0.405519,-1.473449,2.079788,1.130750,0.698079,2.348087,-1.068253,0.561672,-0.704907,-0.063179,1.006803,-0.717055,-0.570055
240,0.621021,0.678680,-0.891925,-0.312939,0.228825,-0.425879,-1.068253,-0.385553,1.418626,1.467932,-0.621650,0.305491,1.126035

# Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
model2 = RandomForestClassifier(n_estimators = 150)

In [ ]:
# it will implement total 150 decision tree behind the seen

In [ ]:
model2.fit(X_train,y_train)

RandomForestClassifier(n_estimators=150)

In [ ]:
y_pred2 = model2.predict(X_test)

In [ ]:
y_pred2 # random forest predicted output

array([1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1])

In [ ]:
y_test

     target
342       1
191       1
349       0
288       1
56        1
..      ...
182       0
878       0
27        0
128       1
102       1

[61 rows x 1 columns]

In [ ]:
 # Performance checking
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred2))

0.819672131147541